import Footer from '@/components/frontend/footer'
import Navbar from '@/components/frontend/navbar'
import React from 'react'

const page = () => {
  return (
    <div>
        <Navbar/>
        <a>a</a>
        <br/>
        <a>a</a>
        <br/>
        <a>a</a>
        <br/>
        <a>a</a>
        <br/>
        <a>a</a>
        <br/>
        <a>a</a>
        <br/>
        <a>a</a>
        <br/>
        <a>a</a>
        <br/>
        <a>a</a>
        <br/>
        <a>a</a>
        <br/>
        <a>a</a>
        <br/>
        <a>a</a>
        <br/>
        <a>a</a>
        <br/>
        <a>a</a>
        <br/>
        <a>a</a>
        <br/>
        <a>a</a>
        <br/>
        <a>a</a>
        <br/>
        <a>a</a>
        <br/>
        <a>a</a>
        <br/>
        <a>a</a>
        <br/>
        <a>a</a>
        <br/>
        <a>a</a>
        <br/>
        <a>a</a>
        <br/>
        <a>a</a>
        <br/>
        <a>a</a>
        <br/>
        <a>a</a>
        <br/>
        <a>a</a>
        <br/>
        <a>a</a>
        <br/>
        <a>a</a>
        <br/>
        <a>a</a>
        <br/>
        <a>a</a>
        <br/>
        <a>a</a>
        <br/>
        <a>a</a>
        <br/>
        <a>a</a>
        <br/>
        <a>a</a>
        <br/>
        <a>a</a>
        <br/>
        <a>a</a>
        <br/>
        <a>a</a>
        <br/>
        <a>a</a>
        <br/>
        <a>a</a>
        <br/>
        <a>a</a>
        <br/>
        <a>a</a>
        <br/>
        <a>a</a>
        <br/>
        <a>a</a>
        <br/>
        <a>a</a>
        <br/>
        <a>a</a>
        <br/>
        <a>a</a>
        <br/>
        <a>a</a>
        <br/>
        <a>a</a>
        <br/>
        <a>a</a>
        <br/>
        <a>a</a>
        <br/>
        <a>a</a>
        <br/>
        <a>a</a>
        <br/>
        <a>a</a>
        <br/>
        <a>a</a>
        <br/>
        <a>a</a>
        <br/>
        <a>a</a>
        <br/>
        <a>a</a>
        <br/>
        <a>a</a>
        <br/>
        <a>a</a>
        <br/>
        <a>a</a>
        <br/>
        <a>a</a>
        <br/>
        <Footer/>
    </div>
  )
}

export default page
